### PR TITLE
Build-1049 About Page Column Callout slice

### PR DESCRIPTION
**Pull request by k-milbury**
**Build-1049 About Page Column Callout slice**
https://app.clickup.com/t/9009201449/BUILD-1049

**Changes**
Added the slice this was missing from the about page
image

**Testing**
Pull PR branch
`yarn install`
`yarn start`
Go to http://localhost:8000/about
View the slice and test it for mobile
[Figma Design](https://www.figma.com/design/VUxtgRSA7pJLgdp50o0N7y/Design-Studio?node-id=3855-5674&node-type=frame&m=dev)

**Slice**
image

**Notes**
I can't get them to shrink evenly on tablet for some reason
image

### CODE REVIEW

**Comment by kirstenjvd** [comment]
Task linked: [BUILD-1049 Missing Section on About Page](https://app.clickup.com/t/9009201449/BUILD-1049)

**Comment by FayeMao** [comment]
Not sure if its a cache issue for me, but I see this large gap after the section?:

image

**Review by FayeMao — APPROVED** [review]
Looking good! I played around with it too and I couldn't get them to be the same size either. Looks like the image wrap gets bigger at some point in tablet size?

**Comment by FayeMao** [comment]
Maybe something like this below? I removed the aspect-ratio from the image-wrap and set it as a fixed image, which seemed to help:

```
.imageWrap {
      width: 250px;
      height: 250px;
      background: black; // CHANGE BG BACK
      display: flex;
      justify-content: center;
      align-items: center;
      padding: 15px;
      @media (min-width: $tablet) {
        padding: 25px;
      }
    }

    .image {
      width: 100%;
      height: 100%;
      border-radius: 99em;
      display: block;
      margin: 0 auto;
      border: 10px solid $color-white;
      background-size: cover;
      @media (min-width: $tablet) {
        
      }

      img {
        width: 100%;
        height: 100%;
        object-fit: cover;
      }
    }

```

**Pull request merged**
